import { LogoText } from '@/components/elements/LogoText';
import Head from 'next/head';

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          style={{
            position: 'fixed',
            top: '0',
            zIndex: 10,
            filter: 'invert(100%)',
            mixBlendMode: 'exclusion',
          }}
        >
          <LogoText text="Daichan 132" />
        </div>
        <div style={{ backgroundColor: 'white', height: '200px' }} />
        <div style={{ backgroundColor: 'black', height: '200px' }} />
        <div style={{ backgroundColor: 'white', height: '200px' }} />
        <div style={{ backgroundColor: 'black', height: '200px' }} />
        <div style={{ backgroundColor: 'white', height: '200px' }} />
        <div style={{ backgroundColor: 'black', height: '200px' }} />
        <div style={{ backgroundColor: 'white', height: '200px' }} />
        <div style={{ backgroundColor: 'black', height: '200px' }} />
        <div style={{ backgroundColor: 'white', height: '200px' }} />
        <div style={{ backgroundColor: 'black', height: '200px' }} />
        <div style={{ backgroundColor: 'white', height: '200px' }} />
      </main>
    </>
  );
};
export default Home;
